### ISSUE TITLE
あとがきの日付

### ISSUE THREAD

**Issue by junsora** [onestop-techbook/Agile100#58]
間違ってなければissue閉じてもらえればと思います。

親方さんのメッセージが2021 年 2 月になってますけど、そんなに前で大丈夫でしたっけ？
2022年 2月 だったりするかなと思ったので。

**Comment by oyakata2438** [comment]
ありがとうございます。
これは別の本のあとがきからそのまま直してないだけですね。
もう少ししたらあとがき書き直すので、その時に修正します。発行日も決まってるはずですしね。
